### ISSUE TITLE
The 'Postal Code' and 'City' field incorrectly displays a dropdown icon in safari browser .

### ISSUE THREAD

**Issue by preetamrevankar** [juspay/hyperswitch-web#734]
steps to reproduce 
Bank of america connector >> open demo store in safari browser >>click  on postal code and city 

![Image](https://github.com/user-attachments/assets/734cfc32-c50a-48e8-be08-538f092a2ee9)
![Image](https://github.com/user-attachments/assets/f725f122-2fd3-48ac-9a44-e00ab4947428)

**Comment by aritro2002** [comment]
This issue occurs due to Safari’s built-in AutoFill settings. Even if you disable autocomplete with `autocomplete="off"` or apply CSS tricks, Safari will still show the AutoFill icon for specific fields like name, password, or card details.

The only reliable way to prevent this behavior is by disabling the AutoFill feature directly in Safari's browser settings. Unfortunately, no combination of frontend changes (CSS or HTML attributes) can fully prevent this icon from appearing for these sensitive fields.

Steps to remove the icon:
1. open safari browser.
2. open developer settings.
3. go to auto fill section and unselect all options.
<img width="826" alt="Screenshot 2024-10-22 at 4 03 56 PM" src="https://github.com/user-attachments/assets/27d34023-243b-44c7-846d-f12fd0000139">


before following the steps:
<img width="1082" alt="Screenshot 2024-10-22 at 4 36 37 PM" src="https://github.com/user-attachments/assets/680cb814-f67b-40c9-a1be-fea8de0e28d1">


after following the steps:
<img width="519" alt="Screenshot 2024-10-22 at 4 35 30 PM" src="https://github.com/user-attachments/assets/3c9084f5-714d-49e5-8036-e57af4fd9b94">
